classewatches/app/urls.py
from django.urls import path
from . import views

app_name='app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('success', views.SuccessView.as_view(), name='success'),

    # Auth
    path('auth/signup', views.SignUpView.as_view(), name='signup'),
    path('auth/login', views.LoginView.as_view(), name='login'),
    path('auth/logout', views.LogoutView.as_view(), name='logout'),
    # Password (forgot and switch)
    path('auth/password/forgot', views.ForgotPasswordView.as_view(), name='forgot_pass'),
    path('auth/password/switch', views.SwitchPasswordView.as_view(), name='switch_pass'),

    # User and Admin
    path('user/admin', views.AdminView.as_view(), name='admin'),
    # User
    path('user/admin/update/<int:pk>', views.UpdateUserView.as_view(), name='update_user'),
    path('user/admin/delete/<int:pk>', views.DeleteUserView.as_view(), name='delete_user'),
    path('user', views.UserView.as_view(), name='user'),

    # Order
    path('user/admin/order/update/<slug:pk>', views.OrderUpdateView.as_view(), name='update_order'),
    path('user/admin/order/details/<slug:pk>', views.OrderDetailsView.as_view(), name='details_order'),
    path('user/admin/order/create', views.OrderCreateView.as_view(), name='create_order'),
    
    # Products
    path('user/admin/products/create', views.CreateProductView.as_view(), name='create_product'),
    path('user/admin/products/update/<int:pk>', views.UpdateProductView.as_view(), name='update_product'),
    path('user/admin/products/delete/<int:pk>', views.DeleteProductView.as_view(), name='delete_product'),

    # Products
    path('products', views.ProductsView.as_view(), name='products'),
    path('products/details/<int:pk>', views.ProductsDetailsView.as_view(), name='product_details'),
    
    # Cart
    path('cart/<int:pk>', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:id>', views.remove_from_cart, name='remove_from_cart'),
    
    # Shipping
    path('payment/shipping', views.ShippingView.as_view(), name='shipping'),
    path('payment/checkout', views.CheckoutView.as_view(), name='checkout')
]

classewatches/classewatches/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classewatches/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuário")
    total = models.FloatField(default=0.00, verbose_name="Total")
    shipping = models.FloatField(default=0.00, verbose_name="Frete")

    def __str__(self):
        return str("Carrinho pertence ao usuário {0}, e tem um id {1}!".format(self.user.username, self.id))

class Product(models.Model):
    id = models.AutoField(primary_key=True)

    # Many-to-many
    cart = models.ManyToManyField(Cart, editable=False, verbose_name="Carrinho")

    title = models.CharField(max_length=25, verbose_name="Título")
    description = models.CharField(max_length=150, verbose_name="Descrição")
    price = models.FloatField(default=0.00, verbose_name="Preço")
    quantity = models.IntegerField(default=1, verbose_name="Quantidade")

    # Images
    image_cover = models.FileField(upload_to='static/', verbose_name="Imagem de capa", help_text="Por favor, tire a foto na vertical.")
    image2 = models.FileField(upload_to='static/', verbose_name="Imagem 2", help_text="Por favor, tire a foto na vertical.")
    image3 = models.FileField(upload_to='static', verbose_name="Imagem 3", help_text="Por favor, tire a foto na vertical.")

    def __str__(self):
        return str("Produto {0} tem id {1}, temos {2} unidade(s) em estoque. O produto custa R$ {3}!".format(self.title, self.id, self.quantity, self.price))


class Order(models.Model):
     
    STATUS_ENUM = [
        ('pendente', 'pendente'),
        ('aceito', 'aceito'),
        ('despachado', 'despachado')
    ]
    
    id = models.SlugField(max_length=900, primary_key=True, null=False)
    first_name = models.CharField(null=False, max_length=150, verbose_name='Primeiro nome')
    last_name = models.CharField(null=False, max_length=150, verbose_name='Sobrenome')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name="Carrinho")
    products = models.ManyToManyField(Product, verbose_name="Produtos")
    total = models.FloatField(default=0.00, verbose_name="Total")
    order_date = models.DateField(default=timezone.now, auto_now_add=False, verbose_name="Data do pedido")
    phone_number = models.CharField(max_length=14, verbose_name="Telefone")
    phone_number2 = models.CharField(max_length=14, verbose_name="Telefone 2")
    state = models.CharField(max_length=25, verbose_name="Estado")
    city = models.CharField(max_length=50, verbose_name='Cidade')
    apartment = models.CharField(null=True, default='S/N', verbose_name="Número da residência", help_text="Anule, se não tiver")
    floor = models.CharField(null=True, help_text="Anule, se não tiver", default='S/N', max_length=6, verbose_name="Andar", )
    district = models.CharField(max_length=25, verbose_name="Bairro")
    street = models.CharField(max_length=25, verbose_name="Rua")
    street_number = models.IntegerField(verbose_name="Número da rua")
    complement = models.CharField(max_length=150, null=True, verbose_name="Complemento")
    postal_code = models.CharField(verbose_name="CEP", max_length=150)
    status = models.CharField(choices=STATUS_ENUM, verbose_name="Status", default=STATUS_ENUM[0][1], max_length=25)
    tracking_link = models.URLField(verbose_name="Link de rastreamento", null=True, default="Não despachado")

    def __str__(self):
        return str(f"Pedido de {self.cart.user.username}, em {self.order_date.day}/{self.order_date.month}/{self.order_date.year}")

classewatches/app/templates/app/cart/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Carrinho{% endblock title %}

{% block content %}
{% include 'header.html' %}
{% include 'back.html' %}

<main class="container">
    {% for product in Cart.product_set.all %}
    <div class="container mb-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-8">
                <div class="p-2">
                    <h4>{{ product.title }}</h4>
                </div>
                <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
                    <div class="mr-1"><img class="rounded" src="{{ product.image_cover.url }}" width="70"></div>
                    <div>
                        <h5 class="text-grey">R$ {{ product.price }}</h5>
                    </div>
                    <form method="post" action="{% url 'app:remove_from_cart' product.id %}"
                        class="d-flex align-items-center">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link text-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash3" viewBox="0 0 16 16">
                                <path
                                    d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                            </svg>
                        </button>
                    </form>
                </div>

            </div>
        </div>
    </div>
    {% empty %}
    <div>
        <h1 class="text-center display-6 fw-bold">Nenhum produto no seu carrinho...</h1>
        <p class="lead text-center fs-6 my-5">Quer encomendar algo? Me contate!</p>
    </div>
    {% endfor %}
    {% if not Cart.product_set.count <= 0 %}
    <p class='lead text-center'>Total: <strong class="text-success fw-bold">R$ {{ total }}</strong></p>
    <div class="bg-white d-flex justify-content-end flex-row align-items-center mt-3 p-2">
        <a href="{% url 'app:shipping' %}" class="btn btn-block btn-lg ml-2 bg-dark text-light" type="button">Prosseguir para envio</a>
    </div>
    {% endif %}
</main>
{% endblock content %}