classewatches/app/urls.py
from django.urls import path
from . import views

app_name='app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('success', views.SuccessView.as_view(), name='success'),

    # Auth
    path('auth/signup', views.SignUpView.as_view(), name='signup'),
    path('auth/login', views.LoginView.as_view(), name='login'),
    path('auth/logout', views.LogoutView.as_view(), name='logout'),
    # Password (forgot and switch)
    path('auth/password/forgot', views.ForgotPasswordView.as_view(), name='forgot_pass'),
    path('auth/password/switch', views.SwitchPasswordView.as_view(), name='switch_pass'),

    # User and Admin
    path('user/admin', views.AdminView.as_view(), name='admin'),
    # User
    path('user/admin/update/<int:pk>', views.UpdateUserView.as_view(), name='update_user'),
    path('user/admin/delete/<int:pk>', views.DeleteUserView.as_view(), name='delete_user'),
    path('user', views.UserView.as_view(), name='user'),

    # Order
    path('user/admin/order/update/<slug:pk>', views.OrderUpdateView.as_view(), name='update_order'),
    path('user/admin/order/details/<slug:pk>', views.OrderDetailsView.as_view(), name='details_order'),
    path('user/admin/order/create', views.OrderCreateView.as_view(), name='create_order'),
    
    # Products
    path('user/admin/products/create', views.CreateProductView.as_view(), name='create_product'),
    path('user/admin/products/update/<int:pk>', views.UpdateProductView.as_view(), name='update_product'),
    path('user/admin/products/delete/<int:pk>', views.DeleteProductView.as_view(), name='delete_product'),

    # Products
    path('products', views.ProductsView.as_view(), name='products'),
    path('products/details/<int:pk>', views.ProductsDetailsView.as_view(), name='product_details'),
    
    # Cart
    path('cart/<int:pk>', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:id>', views.remove_from_cart, name='remove_from_cart'),
    
    # Shipping
    path('payment/shipping', views.ShippingView.as_view(), name='shipping'),
    path('payment/checkout', views.CheckoutView.as_view(), name='checkout')
]

classewatches/classewatches/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classewatches/app/templates/app/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Encontre relógios de pulso{% endblock title %}

{% block content %}
<main class="container-fluid p-5 shadow-lg mb-5 bg-body-tertiary">

    <div class="p-2">
        <img class="d-block mx-auto sticky" src="{% static 'app/images/logo.png' %}" />

        <h1 class="fw-bolder display-1 text-light">Classe Watches</h1>

        <h1 class="fw-bold display-6 text-warning">Encontre relógios de pulso</h1>

        <p class="mt-2 lead text-light">Localizado em Minas Gerais</p>

    </div>

    <div class="my-2" class="button-group" role="group">
        <a href="{% url 'app:products' %}" class="btn btn-dark btn-lg">Produtos</a>

        {% if request.user.is_authenticated and not request.user.is_superuser %}
        <a href="{% url 'app:user' %}" class="btn btn-outline-light btn-lg">Olá {{ request.user.username }}</a>
        {% elif request.user.is_superuser and request.user.is_authenticated %}
        <a href="{% url 'app:admin' %}" class="btn btn-outline-light btn-lg">Olá {{ request.user.username }}</a>
        {% else %}
        <a href="{% url 'app:login' %}" class="btn btn-outline-light btn-lg">Entrar</a>
        {% endif %}
    </div>

</main>

<style>
    main {
        background-image: url("{% static 'app/images/background.jpg' %}");
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
{% endblock content %}