classewatches/app/urls.py
from django.urls import path
from . import views

app_name='app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('success', views.SuccessView.as_view(), name='success'),

    # Auth
    path('auth/signup', views.SignUpView.as_view(), name='signup'),
    path('auth/login', views.LoginView.as_view(), name='login'),
    path('auth/logout', views.LogoutView.as_view(), name='logout'),
    # Password (forgot and switch)
    path('auth/password/forgot', views.ForgotPasswordView.as_view(), name='forgot_pass'),
    path('auth/password/switch', views.SwitchPasswordView.as_view(), name='switch_pass'),

    # User and Admin
    path('user/admin', views.AdminView.as_view(), name='admin'),
    # User
    path('user/admin/update/<int:pk>', views.UpdateUserView.as_view(), name='update_user'),
    path('user/admin/delete/<int:pk>', views.DeleteUserView.as_view(), name='delete_user'),
    path('user', views.UserView.as_view(), name='user'),

    # Order
    path('user/admin/order/update/<slug:pk>', views.OrderUpdateView.as_view(), name='update_order'),
    path('user/admin/order/details/<slug:pk>', views.OrderDetailsView.as_view(), name='details_order'),
    path('user/admin/order/create', views.OrderCreateView.as_view(), name='create_order'),
    
    # Products
    path('user/admin/products/create', views.CreateProductView.as_view(), name='create_product'),
    path('user/admin/products/update/<int:pk>', views.UpdateProductView.as_view(), name='update_product'),
    path('user/admin/products/delete/<int:pk>', views.DeleteProductView.as_view(), name='delete_product'),

    # Products
    path('products', views.ProductsView.as_view(), name='products'),
    path('products/details/<int:pk>', views.ProductsDetailsView.as_view(), name='product_details'),
    
    # Cart
    path('cart/<int:pk>', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:id>', views.remove_from_cart, name='remove_from_cart'),
    
    # Shipping
    path('payment/shipping', views.ShippingView.as_view(), name='shipping'),
    path('payment/checkout', views.CheckoutView.as_view(), name='checkout')
]

classewatches/classewatches/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classewatches/app/templates/app/admin/index.html
{% extends 'base.html' %}

{% block title %} - Administração{% endblock title %}

{% comment 'Descrevendo o template' %}
Este template vai dar acesso completo as models "User", "Product" e "Order"
{% endcomment %}

{% block content %}
{% include 'back.html' %}
{% include 'logout.html' %}

<main class="container-fluid">

    <a href={% url 'app:user' %} class="btn btn-link d-block mx-auto p-2">Meu usuário</a>
    <h1 class="display-4 text-center fw-bolder">Olá administrador, <strong>{{ request.user.username|capfirst }}
    </h1>
    <p class="text-center lead">Bem vindo</p>

    <section class="my-5">
        <canvas id="myChart"></canvas>
    </section>

    <section class="container-fluid">

        {# Order model #}
        <div class="row d-flex justify-content-center bg-light my-5 card p-3">
            <div class="d-flex justify-content-end">
                <a href="{% url 'app:create_order' %}" class="btn btn-sm btn-link text-info fw-bold">Criar</a>
            </div>
            <h2 class="text-center">Pedidos <span class="badge" style="background-color: red;">New</span></h2>
            <details>
                <summary>Ver mais</summary>

                <ul class="list-group list-group-horizontal flex-wrap overflow-scroll">
                    {% for order in Order %}
                    <li class="list-group-item">
                        <small class="text-wrap fw-lighter">{{ order }}</small>
                        <span> | </span>
                        <div class="btn-group" role="group">
                            <a href="{% url 'app:details_order' order.id %}" class="btn btn-sm btn-warning">Detalhes</a>
                            <a href="{% url 'app:update_order' order.id %}" class="btn btn-sm btn-info">Editar</a>
                    </li>
                    {% endfor %}
                </ul>
            </details>
        </div>

        {# product model #}
        <div class="row d-flex justify-content-center bg-light my-5 card p-3">
            <div class="d-flex justify-content-end">
                <a href="{% url 'app:create_product' %}" class="btn btn-sm btn-link text-info fw-bold">Criar</a>
            </div>
            <h2 class="text-center">Produtos <span class="badge text-dark" style="background-color: yellow;">New</span></h2>
            <details>
                <summary>Ver mais</summary>

                <ul class="list-group list-group-horizontal flex-wrap">
                    {% for product in Product %}
                    <li class="list-group-item">
                        <small class="text-wrap fw-lighter">{{ product }}</small>
                        <span> | </span>
                        <div class="btn-group" role="group">
                            <a href="{% url 'app:update_product' product.id %}" class="btn btn-sm btn-info">Editar</a>

                            <!-- Button trigger modal -->
                            <button data-bs-toggle="modal" data-bs-target="#deleteProduct"
                                class="btn btn-sm btn-danger">Excluir</button>

                            <!-- Modal -->
                            <form method="post" action="{% url 'app:delete_product' product.id %}">
                                {% csrf_token %}
                                <div class="modal fade text-danger" id="deleteProduct" tabindex="-1"
                                    aria-labelledby="deleteProduct" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="deleteProduct">ATENÇÃO</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Tem certeza que deseja excluir esse produto? Essa operação não poderá
                                                ser desfeita
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Não</button>
                                                <button type="submit" type="button" class="btn btn-danger">Sim</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        </form>

                    </li>
                    {% endfor %}
                </ul>
            </details>
        </div>

        {# User model #}
        <div class="row d-flex justify-content-center bg-light my-5 card p-3">
            <div class="d-flex justify-content-end">
                <a href="{% url 'app:signup' %}" class="btn btn-sm btn-link text-info fw-bold">Criar</a>
            </div>
            <h2 class="text-center">Usuários <span class="badge" style="background-color: blue;">New</span></h2>
            <details>
                <summary>Ver mais</summary>

                <ul class="list-group overflow-scroll">
                    {% for user in User %}
                    <li class="list-group-item">
                        <small class="text-wrap fw-lighter">Usuário {{ user.username|capfirst }}</small>
                        <span> | </span>
                        <div class="btn-group" role="group">
                            <a href="{% url 'app:update_user' user.id %}" class="btn btn-sm btn-info">Editar</a>

                            <!-- Button trigger modal -->
                            <button data-bs-toggle="modal" data-bs-target="#deleteUser"
                                class="btn btn-sm btn-danger">Excluir</button>

                            <!-- Modal -->
                            <form method="post" action="{% url 'app:delete_user' user.id %}">
                                {% csrf_token %}
                                <div class="modal fade text-danger" id="deleteUser" tabindex="-1"
                                    aria-labelledby="deleteUser" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="deleteUser">ATENÇÃO</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Tem certeza que deseja excluir esse usuário? Essa operação não poderá
                                                ser desfeita
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Não</button>
                                                <button type="submit" type="button" class="btn btn-danger">Sim</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        </form>

                    </li>
                    {% endfor %}
                </ul>
            </details>
        </div>

    </section>
</main>

{# Data sets #}
<input id="product-ds" type="hidden" name="products" value="{{ Product.count }}">
<input id="order-ds" type="hidden" name="orders" value="{{ Order.count }}">
<input id="user-ds" type="hidden" name="users" value="{{ User.count }}">

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<script>
    var xValues = ["Pedidos", "Produtos", "Usuários"];
    // Insert data from products, users and orders
    productDs = document.getElementById('product-ds').value
    orderDs = document.getElementById('order-ds').value
    userDs = document.getElementById('user-ds').value

    var yValues = [orderDs, productDs, userDs];
    var barColors = [
        "red",
        "yellow",
        "blue"
    ];

    new Chart("myChart", {
        type: "pie",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            title: {
                display: true,
                text: "Classe Watches Chart"
            }
        }
    });
</script>

{% endblock content %}